os:
  - linux

language: php

php:
  - '7.2'
  
before_script:
  - composer self-update
  - composer install --no-interaction
  - npm install npm@latest -g
  - npm install
  
script:
  - vendor/bin/phpunit
  - npm run production